# Generated by Django 3.1.4 on 2021-01-07 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150, null=True)),
                ('muscle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rest_time', models.IntegerField(default=30)),
                ('exercise_time', models.IntegerField(default=30)),
                ('exercise', models.ManyToManyField(to='user.Exercise')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOutDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.workout')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Newbie', 'Newbie'), ('Intermediate', 'Intermediate'), ('Ace', 'Ace'), ('The Rock', 'The Rock')], default='Newbie', max_length=20)),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('completed_workouts', models.ManyToManyField(blank=True, null=True, related_name='completed_workouts', to='user.WorkOutDate')),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_instructor', to='instructor.instructor')),
                ('pending_workouts', models.ManyToManyField(blank=True, null=True, related_name='pending', to='user.WorkOutDate')),
                ('requests', models.ManyToManyField(blank=True, null=True, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
