# Generated by Django 3.1.4 on 2021-01-07 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210107_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='test',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='user.testdb'),
            preserve_default=False,
        ),
    ]
