# Generated by Django 3.1.4 on 2021-01-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210107_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='user.testdb'),
        ),
    ]
